project:
  type: "default"
  execute-dir: "project"
  render:
    - "workbooks/dataset_seurat.qmd"
    
format:
  html:
    theme:
    - "serif"
    - "css/html.scss"
    knitr:
      opts_chunk:
        echo: true
        warning: false
        fig-width: 8
        fig-height: 5
        dev:
        - "png"
        dev.args:
          type: "cairo"
  revealjs:
    theme:
    - "serif"
    - "css/revealjs.scss"
    smaller: true
    auto-stretch: false
    df-print: "default"
    knitr:
      opts_chunk:
        echo: true
        warning: false
        collapse: true
        fig-width: 8
        fig-height: 5
        dev:
        - "png"
        dev.args:
          type: "cairo"

