project:
  type: "default"
  execute-dir: "project"
  render:
    - "workbooks/dataset_seurat.qmd"

####################
# Execute defaults #
####################
execute: 
  echo: true
  warning: false
  
#################
# Knitr options #
#################
knitr:
  opts_chunk:
    dpi: 300
    fig-width: 8
    fig-height: 5
    dev:
    - "png"
    - "cairo_pdf"
    dev.args:
      png:
        type: "cairo"
    
##################
# Format options #
##################
format:
  html:
    theme: "serif"
  revealjs:
    theme:
    - "serif"
    - "css/revealjs.scss"
    smaller: true
    auto-stretch: false
    df-print: "default"
    knitr:
      opts_chunk:
        collapse: true

