project:
  type: "default"
  execute-dir: "project"
  render:
    - "workbooks/our_first_workbook.qmd"
    - "workbooks/read_dataset_to_seurat.qmd"
    - "workbooks/analyze_spatial_dataset.qmd"

####################
# Execute defaults #
####################
execute: 
  echo: true
  warning: false
  
#################
# Knitr options #
#################
knitr:
  opts_chunk:
    timeit: null
    dpi: 400
    fig-width: 8
    fig-height: 5
    dev:
    - "png"
    dev.args:
      png:
        type: "cairo"
    
##################
# Format options #
##################
format:
  html:
    theme:
    - "serif"
    - "css/html.scss"

