project:
  type: default
  execute-dir: project
  render:
    - "workbooks/dataset_seurat.qmd"
    
format:
  html:
    theme: serif
    knitr:
      opts_chunk:
        echo: true
        warning: false
        dev: "CairoPNG"
  revealjs:
    theme:
    - serif
    - "css/revealjs.scss"
    smaller: true
    auto-stretch: false
    df-print: default
    knitr:
      opts_chunk:
        echo: true
        warning: false
        dev: "CairoPNG"


