---
title: "Preparation"
---

## Things to

- Send list of participants (name, email, institution) to Falk

- Need vpn and ssh access as well as access to biocluster4 
- Distribute RStudio Server to the following cluster nodes c-2-0, c-2-2, c-2-3, c-2-4
- Five per node, 20 cores and 72Gb RAM each
- Tunnel communication via biocluster4

- Students should work in the homes
- Dataset is big (10Gb) - need 40Gb
- We would like to prepare the homes:
  - Download our git repo
  - Create RStudio project
  - Download dataset

## Set up basic things

- connect to wlan
- connect to home directory (windows: connect in explorer, linux: sshfs, mac: sshfs or mac explorer)
- open a file in file explorer
- explore home directory (windows/mac explorer?), also show training directory
- handout so that they can check
- set up ssh (host name, user, password, tunnel, proxy?)

## Start RStudio server

- login to biocluster4
- submit rstudio server batch script (only once, runs for three days)
- check if rstudio server is running, see log file, then (open browser, localhost:8787, user:password)


## Intro to RStudio

- Load the training project

Start rserver


